select * from laksh.sample;
select age_of_woman from laksh.sample;
select * from laksh.sample limit4;
select * from laksh.sample;
select distinct age_of_woman from laksh.sample;
select * from laksh.sample;
select * from laksh.sample where age_of_woman = '45 and over';
insert into laksh.sample values ('2023', '60', '300');
select * from laksh.sample;
select distinct age_of_woman from laksh.sample;
select distinct age_of_woman from laksh.sample order by age_of_woman;
select distinct age_of_woman from laksh.sample order by age_of_woman desc;
select count(distinct age_of_woman) from laksh.sample;
select count(*) from laksh.sample;
delete from laksh.sample where Period = '2023';
select * from laksh.sample;